// <auto-generated />
namespace Munchkin_Online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UInttoInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UInttoInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201409191924388_UInt-to-Int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
